fix: `adopt_orphan_extensions` + schema extensions + implicit root operation interaction (#907)
Building a schema with the `adopt_orphan_extensions` option enabled yields an error in the following simple case:
```graphql
extend schema { query: Query }

type Query { x: Int }
```

```
Error: duplicate definitions for the `query` root operation type
   ╭─[schema.graphql:2:25]
   │
 2 │         extend schema { query: Query }
   │                         ──────┬─────  
   │                               ╰─────── `query` redefined here
───╯
```

Currently, it accidentally makes the assumption that a schema extension's root operations do not use a default name, which explains why [this test](https://github.com/apollographql/apollo-rs/blob/caf820d86a03db3650149cefe6157442c73d7e50/crates/apollo-compiler/tests/extensions.rs#L5-L10) currently passes but the failing test from [f3f95b8](https://github.com/apollographql/apollo-rs/pull/907/commits/f3f95b8e65b4f4988843fd9151a7ffbfa70d9125) did not. This results in the `query` root operation type being added twice - once at the implicit step, and again when the orphan extensions are applied.

In the case that `adopt_orphan_extensions` is enabled, we need to scan the orphan schema extensions for root operations that match the default name and _skip_ the implicit addition step if so, since the extensions will be applied in a subsequent step.